figure; 
plot(accelTime, cleanAccelData); 
title('Cleaned Accelerometer Data'); 
xlabel('Time (s)'); 
ylabel('Acceleration (m/s^2)'); 
figure; 
plot(gyroTime, cleanGyroData); 
title('Cleaned Gyroscope Data'); 
xlabel('Time (s)'); 
ylabel('Angular Velocity (rad/s)'); 
figure; 
plot(orientTime, cleanOrientData); 
title('Cleaned Orientation Data'); 
xlabel('Time (s)'); 
ylabel('Orientation (degrees)'); 
figure; 
plot(positionTime, cleanPositionData); 
title('Cleaned Position Data'); 
xlabel('Time (s)'); 
ylabel('Position (m)'); 